version: '3'

networks:
  cleaver:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: site
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - cleaver

  php:
    image: php:7.4-fpm-alpine
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - cleaver
